databases:
  - name: slotsdb
    plan: free
    databaseName: gtec/Joelscariajustine123 Project
    user: postgres

services:
  - type: web
    plan: free
    name: slot
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn slot.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        value: "postgres://postgres:gtec12345678@db.qipgxmxohtpkxbsvtrih.supabase.co:5432/postgres"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
